-- Inspired by LunarVim:
-- https://github.com/LunarVim/LunarVim/blob/28dbec26c36a24669c95798b5949f1f48d3f32e0/lua/lvim/icons.lua
return {
  kind = {
    Array = "",
    Boolean = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "",
    Module = "",
    Namespace = "",
    Null = "ﳠ",
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
  },
  diagnostics = {
    hint = "󰌵",
    info = "",
    warning = "",
    error = "",
  },
  ui = {
    Breakpoint = "",
  }
}
